- hosts: all
  become: true
  tasks:
    - name: Stop swap
      command: swapoff -a

    - name: Disable swap at boot
      replace:
        path: /etc/fstab
        regexp: ^([^#].*\sswap\s.*)$
        replace: '# \1'

    - name: Configure kernel modules for Kubernetes
      lineinfile:
        path: /etc/modules-load.d/k8s.conf
        line: "{{ item }}"
        create: yes
      loop:
        - overlay
        - br_netfilter

    - name: Configure sysctl params for Kubernetes
      lineinfile:
        path: /etc/sysctl.d/k8s.conf
        line: "{{ item }}"
        create: yes
      with_items:
        - 'net.bridge.bridge-nf-call-iptables  = 1'
        - 'net.ipv4.ip_forward                 = 1'
        - 'net.bridge.bridge-nf-call-ip6tables = 1'

    - name: Add Docker official GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

    - name: Add Docker repository
      apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        filename: docker
        update_cache: yes

    - name: Install Containerd
      apt:
        name: containerd.io
        state: present

    - name: Create Containerd config directory
      file:
        path: /etc/containerd
        state: directory

    - name: Get Containerd config with systemd cgroup driver enabled
      shell: containerd config default | sed 's/SystemdCgroup = false/SystemdCgroup = true/'
      register: get_containerd_config

    - name: Set Containerd config
      copy:
        content: "{{ get_containerd_config.stdout }}"
        dest: /etc/containerd/config.toml

    - name: Enable Containerd at boot
      systemd:
        name: containerd
        enabled: true

    - name: Add Google official GPG key
      get_url:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg

    - name: Add Kubernetes Repository
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] http://apt.kubernetes.io/ kubernetes-xenial main 
        state: present
        filename: kubernetes
        update_cache: yes

    - name: Install Kubernetes packages
      apt:
        name:
          - kubelet={{ KUBERNETES_VERSION }}-00
          - kubeadm={{ KUBERNETES_VERSION }}-00
          - kubectl={{ KUBERNETES_VERSION }}-00
        state: present

    - name: Enable kubelet at boot
      systemd:
        name: kubelet
        enabled: yes

    - name: Install skopeo
      apt:
        name: skopeo
        state: present

    - name: Create Kubernetes container image directory
      file:
        path: /usr/share/capch/images
        state: directory

    - name: List Kubernetes container image
      command: kubeadm config images list --kubernetes-version {{ KUBERNETES_VERSION }}
      register: list_kubernetes_image

    - name: Download Kubernetes container image
      shell: skopeo copy docker://{{ item }} oci-archive:/usr/share/capch/images/$(echo {{ item }} | sed -r 's/[/:]/_/g').tar:{{ item }}
      with_items:
        "{{ list_kubernetes_image.stdout_lines }}"

    - name: Configure sysctl params for Cilium.
      lineinfile:
        path: /etc/sysctl.d/99-override_cilium_rp_filter.conf
        line: "{{ item }}"
        create: yes
      with_items:
        - 'net.ipv4.conf.lxc*.rp_filter = 0'
