name: build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: smartxrocks
          password: ${{ secrets.DOCKERHUB_PUSH_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          file: kernel/Dockerfile
          tags: smartxworks/capch-kernel-5.15.12
          platforms: linux/amd64,linux/arm64
          push: true

      - uses: docker/build-push-action@v2
        with:
          file: rootfs/Dockerfile
          tags: smartxworks/capch-rootfs-1.24.0
          platforms: linux/amd64,linux/arm64
          push: true
